networks:
    hapi-fhir: 
      external: true

services:
  nginx:
      image: nginx:alpine
      container_name: nginx
      restart: unless-stopped
      networks:
        - hapi-fhir
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./../proxy/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./../certs/star.intellisoftkenya.com.crt:/opt/star.intellisoftkenya.com.crt:ro
        - ./../certs/star.intellisoftkenya.com.key:/opt/star.intellisoftkenya.com.key:ro

        