networks:
    hapi-fhir:
        external: true    

services:

    hapi-fhir-postgres:
        container_name: hapi-fhir-postgres
        image: postgres:14-alpine
        restart: always
        networks:
            - hapi-fhir
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: hapi
            POSTGRES_PASSWORD: hapi123
        volumes:
            - 'hapi-fhir-postgres:/var/lib/postgresql/data'

    hapi-fhir-jpa:
        image: intellisoftkenya/hapi-fhir:latest
        container_name: hapi-fhir-jpa
        restart: unless-stopped
        networks:
            - hapi-fhir
        depends_on:
            - hapi-fhir-postgres
        volumes:
            - "./../hapi-fhir:/hapi"
        ports:
            - "8081:8080"
        environment:
            SPRING_CONFIG_LOCATION: /hapi/application.yaml


volumes:
    hapi-fhir-postgres:
