name: Deploy to dev environment
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
jobs:
  build:
    name: Build and Deploy to Dev
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: cd /opt/LHSS-CBDHS-HIE/ && cat pass | sudo -S ./run-hie.sh
