  name: Test Docker Images
  on:
    pull_request:
      branches: [ main ]

  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
  
        - name: Start containers
          run: |
            cp mediators/.env.example mediators/.env
            cp auth/.env.example auth/.env
            docker network create cloudbuild
            docker-compose -f "docker-compose.yml" up -d --build